name: 'nyc_taxi'
version: '1.0.0'
config-version: 2

profile: 'default'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"

clean-targets:
  - "target"
  - "dbt_packages"

models:
  nyc_taxi:
    bronze:
      +materialized: view
      +schema: "{{ env_var('DBT_BRONZE_SCHEMA', 'BRONZE') }}"

    silver:
      +materialized: table
      +schema: "{{ env_var('DBT_SILVER_SCHEMA', 'SILVER') }}"

    gold:
      +materialized: table
      +schema: "{{ env_var('DBT_GOLD_SCHEMA', 'GOLD') }}"