services:
  
  kestra-db:
    image: postgres:17-alpine
    volumes:
      - kestra-db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${K_POSTGRES_DB}
      - POSTGRES_USER=${K_POSTGRES_USER}
      - POSTGRES_PASSWORD=${K_POSTGRES_PASSWORD}

  
  kestra:
    image: kestra/kestra:v1.3.37
    user: "root"
    command: ["server", "standalone"]
    ports:
      - 8080:8080
    environment:
      KESTRA_CONFIGURATION: &common_conf |
        datasources:
          postgres:
            url: jdbc:postgresql://kestra-db:5432/${K_POSTGRES_DB}
            driver-class-name: org.postgresql.Driver
            username: ${K_POSTGRES_USER}
            password: ${K_POSTGRES_PASSWORD}
        kestra:
          server:
            basic-auth:
              username: ${K_USER}
              password: ${K_PASSWORD}
          repository:
            type: postgres
          queue:
            type: postgres
          storage:
            type: local
            local:
              base-path: /app/storage
          tasks:
            tmp-dir:
              path: /tmp/kestra-wd-tmp
        url: http://localhost:8080

        micronaut:
          io:
            watch:
              enabled: true
              paths:
                - /app/flows
    
    volumes:
      - kestra-storage:/app/storage
      - ./kestra/flows:/app/flows
    depends_on:
      - kestra-db


volumes:
  kestra-db-data:
  kestra-storage: